name: RecoverHealth

version: 2.0

author: BryanG
main: me.bryangaming.recoverhealth.RecoverHealth
api-version: 1.16


commands:
  recoverhealth:
    description: The main command.
    aliases:
      - rh
      - recoverh
      - rhealth