#
# RecoverHealth 2.0
# By BryanG.
#

# Permissions:
# - recoverhealth.reload : To reload the plugin.
# - recoverhealth.give : To give the potion.


# Options.
options:
  add-health: 3

# Item name:
item:
  id: GOLD_INGOT
  name: "&aTotem item."
  lore:
    - ""
    - "&aGood luck!"

# When the player use the totem.
# You can watch the actions in the plugin page.
event:
  actions:
    - "[EFFECT] ABSORPTION; 3; 2"
    - "[EFFECT] REGENERATION; 3; 2"
    - "[MESSAGE]&7The item help you..."


