#
# RecoverHealth 2.1
# By BryanG.
#

# Permissions:
# - recoverhealth.reload : To reload the plugin.
# - recoverhealth.give : To give the potion.


# Options.
options:
  add-health: 3

# Item name:
item:
  id: GOLD_INGOT
  name: "&aTotem item."
  lore:
    - ""
    - "&fGood luck!"

# When the player use the totem.
# You can watch the actions in the plugin page.

event:
  actions:
    - "[EFFECT] ABSORPTION; 3; 2"
    - "[EFFECT] REGENERATION; 3; 2"
    - "[MESSAGE] &e[!] &fYou receive totem help."
    - "[SOUND] ENTITY_GENERIC_EXPLODE; 100; 1"


